### ISSUE TITLE
Working Perfect on Localhost, Error When deploying online Server, No video r Audio call

### ISSUE THREAD

**Issue by Usman-Qasim** [ashikmahmud1/node-chat-app#4]
when i am using it on localhost its working perfectly,
but when i deploy it on an online server,

Realtime messaging working perfectly and File sharing too.
But on video and Audio call,
its not working as working on localhost,
No video no Audio.

**Comment by ashikmahmud1** [comment]
> when i am using it on localhost its working perfectly,
> but when i deploy it on an online server,
> 
> Realtime messaging working perfectly and File sharing too.
> But on video and Audio call,
> its not working as working on localhost,
> No video no Audio.

can you please debug the code in real-server and send me exactly what error is happening? so that I can work in resolving the issue.
